/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "REWARDS": "奖励",
    "Save Slot": "存档槽位",
    "Safe": "安全",
    "Save Game": "保存游戏",
    "Build": "建造",
    "STABLE": "稳定",
    "Buildings": "建筑",
    "Command": "指挥",
    "Updates": "更新",
    "Upkeep": "维护",
    "View Events": "查看事件",
    "Territory": "领土",
    "Survivors": "幸存者",
    "Supplies": "供应",
    "Safe Zones": "安全区",
    "Stability": "稳定性",
    "Researched": "已研究",
    "Serum Lab": "血清实验室",
    "Research Technologies": "研究技术",
    "RESEARCH TECH": "研究技术",
    "Research": "研究",
    "Research output": "研究成果",
    "RED ALERT": "红色警报",
    "Queue Slots": "队列槽位",
    "Knowledge": "知识",
    "Events": "事件",
    "Critical": "暴击",
    "Command Center": "指挥中心",
    "Campaign Phase": "活动阶段",
    "Operations": "操作",
    "Build Infrastructure": "建造基础设施",
    "Build Supply Farm to level 5 to sustain ongoing upkeep": "建造补给场至5级以维持持续的维护",
    "Central operations dashboard for outbreak management": "用于爆发管理的中央操作指示板",
    "Expand Territory": "扩张领土",
    "Containment": "控制",
    "Active Events": "活跃事件",
    "Active Missions": "活跃任务",
    "Active Operations": "活跃操作",
    "Go to": "前往",
    "IN DEVELOPMENT": "开发中",
    "Expand": "展开",
    "Intermediate step • Not the final cure": "中间步骤 • 不是最终的解决方案",
    "Phase Reached": "阶段达到",
    "Production": "生产",
    "Play Time": "游戏时长",
    "Prestige bonuses provide starting resources, production boosts, and cost reductions": "声望奖励提供初始资源、产量提升和成本降低",
    "Tip:": "提示:",
    "Technologies": "科技",
    "Try Again": "重试",
    "View Event": "查看事件",
    "Workers": "工人",
    "/s recruitment": "/秒 招聘",
    "Assigned": "分配的",
    "Available": "可用",
    "Controlled": "受控",
    "Morale": "士气",
    "Infrastructure": "基础设施",
    "Infection": "感染",
    "Influence": "影响力",
    "Critical Alerts": "重要提醒",
    "Diplomacy gain": "外交收益",
    "Outbreak Protocol": "爆发协议",
    "Net change": "净变化",
    "Phase": "阶段",
    "Quick Start Guide": "快速入门指南",
    "Start by building Shelters and Farms to generate\n                          Survivors and Supplies—keep an eye on upkeep and pause\n                          buildings if supplies dip": "从建造庇护所和农场开始，生成\n幸存者和补给——注意维护，如果补给减少，暂停\n建筑",
    "Start by building Shelters and Farms to generate Survivors and Supplies—keep an eye on upkeep and pause buildings if supplies dip": "从建造避难所和农场开始，以产生生还者和供给——注意维护，如果供给下降，暂停建造",
    "Build Radio Towers to gain Influence, but only keep\n                          them online when your supply trend is positive": "建造无线电塔来获得影响力，但只有当你的供应趋势是积极的时候才能保持它们在线",
    "Build Radio Towers to gain Influence, but only keep them online when your supply trend is positive": "建造无线电塔来获得影响力，但只有当你的供应趋势是积极的时候才能保持它们在线",
    "Build Labs to generate Knowledge, then research technologies to unlock new capabilities": "建立实验室以产生知识，然后研究技术以解锁新功能",
    "Watch the supply trend in the header—if it turns red, pause non-essential buildings until you recover, then continue pushing objectives.": "观察标题中的供给趋势——如果它变成红色，暂停非必要的建筑直到你恢复，然后继续推进目标。",
    "Active": "活跃",
    "In Progress": "进度",
    "Total Levels": "总等级",
    "Build Radio Tower to level 3 and maintain a positive supply trend": "建立无线电塔到3级，并保持积极的供应趋势",
    "active event(s) requiring attention": "需要关注的活跃事件",
    "Immediate attention required": "需要立即注意",
    "Ancestral Data Earned": "原始数据获得",
    "Breakdown": "详情",
    "Build Containment Units and stabilize red provinces": "建立控制单元，稳定红色省份",
    "Building Levels": "建筑等级",
    "CRITICAL": "危重",
    "CRITICAL INFECTION": "危重感染",
    "CRITICAL: Infection at 100%": "危重：100%感染",
    "Field Missions": "野外任务",
    "In Queue": "在队列中",
    "OPERATION FAILED": "操作失败",
    "The infection has completely overwhelmed humanity. The outbreak is unstoppable.": "这种感染已经使人类不堪重负。爆发是不可阻挡的。",
    "Total Prestige Level:": "总声望等级:",
    "WARNING": "警告",
    "Prestige Restart": "声望重启",
    "Infection rate critical:": "感染率危急：",
    "Required for serum development": "血清发展所需",
    "Research Provisional Vaccine (Tier 4) to unlock": "研究临时疫苗（第四阶）解锁",
    "Provisional Vaccine": "临时疫苗",
    "slots": "槽位",
    "Research Queue": "研究队列",
    "Research completion by tier": "按层级划分的研究完成情况",
    "Resilient Society": "弹性社会",
    "Synthetic Drugs": "合成药物",
    "Tier Progress Overview": "层级进度概览",
    "TIER": "层级",
    "Technologies unlocked": "技术解锁",
    "PREREQUISITES": "先决条件",
    "Mobile Labs": "移动实验室",
    "Locked": "未解锁",
    "lab": "实验室",
    "Infection Rate": "感染率",
    "IDLE": "空闲",
    "Improved agricultural techniques for better supply production": "改进农业技术，提高供应生产",
    "Improved protocols for containing and isolating infected areas": "改进了控制和隔离感染区域的方案",
    "Establish satellite communication for global coordination": "建立卫星通信，促进全球协调",
    "farm": "农业",
    "Efficient Farming": "高效农业",
    "EFFECTS": "效果",
    "Early-stage vaccine that provides temporary immunity": "提供暂时免疫力的早期疫苗",
    "Levels": "等级",
    "First level output:": "一级输出:",
    "Defense": "防御",
    "Net Flow": "网络流",
    "Research Lab": "研究实验室",
    "Radio Tower": "无线电塔",
    "Upkeep: -": "保养: -",
    "Supply Farm": "供应农场",
    "Support": "支持",
    "supplies": "供应",
    "Satellite Uplink": "卫星上行",
    "Serum Synthesis Station": "血清合成站",
    "Specialized facility for containing and studying the infection": "用于控制和研究感染的专门设施",
    "Boost it by resolving crises favorably, providing aid, and keeping supplies steady.": "通过积极解决危机、提供援助和保持供应稳定来促进它。",
    "Captures survivor optimism and willingness to follow orders. Strong morale cushions stability and infection swings.": "捕捉到幸存者的乐观和服从命令的意愿。强大的士气缓冲了稳定和感染的波动。",
    "Containment Coefficient": "控制系数",
    "Drops when morale collapses, infection surges, or territories slip into red status without containment.": "当士气崩溃，感染激增，或领土在没有遏制的情况下进入红色状态时掉落。",
    "Falling behind on research or losing critical infrastructure will stagnate containment gains.": "在研究方面落后或失去关键基础设施将使防控成果停滞不前。",
    "Global Morale": "全球士气",
    "Global Stability": "全球稳定",
    "Indicates how aggressively the outbreak is spreading at this moment. Critical levels can trigger game-ending scenarios if ignored.": "显示了目前疫情蔓延的速度。如果忽视了关键关卡便会触发游戏结局。",
    "Infection Pressure": "感染压力",
    "Invest in research labs, containment units, and specialised technologies to elevate this value.": "投资研究实验室、隔离设施和专业技术来提升这一价值。",
    "It climbs rapidly when morale is low, red provinces stack up, or emergencies are left unresolved.": "当士气低落、红色省份堆积或紧急情况未得到解决时，它会迅速攀升。",
    "Lower the pressure with containment research, stabilised provinces, and events that secure medical or logistic support.": "通过遏制研究、稳定省份和确保医疗或后勤支持的事件来降低压力。",
    "Measures how orderly and coordinated your response network is. Higher stability slows future infection growth and keeps crises at bay.": "衡量你的反应网络有多有序和协调。更高的稳定性减缓了未来感染的增长，避免了危机的发生。",
    "Rises when you secure provinces, resolve events decisively, and maintain healthy morale across survivors.": "当你占领省份，果断地解决事件，并在幸存者中保持健康的士气时上升。",
    "Shows how much infection you suppress every tick. The higher the coefficient, the more the infection rate declines naturally.": "显示出你能抑制多少感染。系数越高，感染率自然下降越多。",
    "Starvation, high casualties, and hard-line ethical choices will erode morale over time.": "随着时间的推移，饥饿、高伤亡和强硬的道德选择将削弱士气。",
    "/s supplies": "/秒 供应",
    "% utilized": "% 利用率",
    "active": "活跃",
    "Advanced education center that accelerates research and boosts morale": "高级教育中心，加速研究，鼓舞士气",
    "All Buildings": "所有建筑",
    "available": "可用",
    "avg": "平均",
    "Broadcasts messages and coordinates efforts, generating influence": "广播信息和协调工作，产生影响",
    "Containment Unit": "收容单元",
    "Global communication network that reduces events and improves containment": "减少事件并改善遏制的全球通信网络",
    "Manufactures tools and equipment, boosting overall production by 0.8% per level": "制造工具和装备，每级提高0.8%的整体产量",
    "Medical Clinic": "医疗诊所",
    "University": "大学",
    "Workforce": "劳动力",
    "workshop": "工坊",
    "Workshop": "工坊",
    "Treats the infected and improves public health": "治疗感染者，改善公众健康",
    "Refugee Shelter": "难民收容所",
    "Provides housing for survivors and slowly increases population": "为幸存者提供住房，慢慢增加人口",
    "Produces supplies through agriculture and resource gathering": "通过农业和资源收集生产供给品",
    "New Event": "新事件",
    "Notification": "通知",
    "Watch the\n                      supply trend in the header—if it turns red, pause\n                      non-essential buildings until you recover, then continue\n                      pushing objectives.": "观察顶部供给趋势——如果它变成红色，暂停非必要的建筑直到你恢复，然后继续推进目标。",
    "% complete": "% 完成",
    "Advanced Containment": "高级收容",
    "Advanced orbital communication network for global reach": "先进的全球轨道通信网络",
    "advanced_decontamination": "高级去污",
    "ALL TIERS": "所有层级",
    "Alpha Synthesis": "阿尔法合成",
    "Available Knowledge": "可用知识",
    "Basic medical training for survivors to reduce infection spread": "为幸存者提供基本医疗培训，以减少感染传播",
    "Biolab Security": "生物学实验室安全",
    "Breakthrough technology for synthesizing the cure serum": "合成治愈血清的突破性技术",
    "Build Labs to generate Knowledge, then research\n                          technologies to unlock new capabilities": "建立实验室以产生知识，然后研究技术以解锁新功能",
    "Build Radio Tower to level 3 and maintain a positive\n                        supply trend": "建立无线电塔到3级，并保持积极的\n供应趋势",
    "Civilian Networks": "民用网络",
    "clinic": "诊所",
    "Develop synthetic medications to treat symptoms and boost morale": "开发合成药物来治疗症状，鼓舞士气",
    "Emergency containment protocol for critical outbreak situations": "紧急疫情控制方案",
    "Emergency Mechanics": "应急机制",
    "Enhanced security protocols for research facilities": "加强研究设施的安全协议",
    "Field Medicine": "领域医学",
    "HIDE RESEARCHED": "隐藏的研究",
    "No active research. Select a technology below to begin.": "没有积极的研究。选择下面的技术开始。",
    "Orbital Communications": "轨道通信",
    "Organize civilian communication networks for better coordination": "组织民用通信网络，加强协调",
    "Overall Progress": "总体进展",
    "Portable research facilities for field deployment": "用于野外部署的便携式研究设施",
    "Protocol Zero": "协议为零",
    "radio_tower": "无线电塔",
    "Ready to research": "准备好研究了吗？",
    "Research & Development": "研发",
    "Research currency for unlocking technologies": "研究解锁技术的货币",
    "satellite_surveillance": "卫星监视",
    "satlink_upgrade": "卫星链路升级",
    "serum_synthesis": "血清合成",
    "Social programs to build a stronger, more resilient community": "建立一个更强大、更有韧性的社区的社会项目",
    "Train survivors in basic repair and maintenance skills": "培训幸存者基本的维修和保养技能",
    "Unlock advanced technologies to improve your response capabilities": "解锁先进技术以提高您的响应能力",
    "Unlocks Feature": "解锁功能",
    "⚠️ This will permanently delete all progress, save files, and settings. This action cannot be undone.": "⚠️ 这将永久删除所有进度、保存文件和设置。此操作不能撤消。",
    "LOCKED": "未解锁",
    "Load Game": "加载游戏",
    "New Total:": "新合计：",
    "Prestige Now": "立即声望",
    "Safe Provinces": "安全的省份",
    "Auto-Save": "自动保存",
    "Auto-Save Status": "自动保存状态",
    "Animation Speed": "动画速度",
    "SYSTEM": "系统",
    "Slot 1 - Primary Save": "槽位 1 - 主存档",
    "Version": "版本",
    "EXPORT / IMPORT": "导出 / 导入",
    "Import Save File": "导入存档文件",
    "Export Save File": "导出存档文件",
    "Display & Interface": "显示 & 界面",
    "Current Phase": "当前阶段",
    "Danger Zone": "危险区",
    "Advance to": "前进到",
    "Automatically save progress every 30 seconds": "每30秒自动保存进度",
    "Begin Synthesis": "开始合成",
    "Build Synthesis Station": "建造合成站",
    "Complete objectives to unlock this critical research facility": "完成目标解锁这个关键的研究设施",
    "Configure system behavior and notifications": "配置系统行为和通知",
    "Configure visual and interface preferences": "配置可视化和界面首选项",
    "Construct the Serum Synthesis Station building": "建设血清合成站大楼",
    "Develop the cure to end the outbreak and save humanity from extinction": "研发解药，终结疫情，拯救人类免于灭绝",
    "Game version and statistics": "游戏版本及统计",
    "Irreversible actions - proceed with extreme caution": "不可逆转的行动——要格外小心",
    "Laboratory Access Restricted": "实验室进入限制",
    "Manage game settings, save files, and preferences": "管理游戏设置，保存文件和首选项",
    "Manage your save files and game progress": "管理您的保存文件和游戏进度",
    "Manual Prestige": "手动声望",
    "Notifications": "通知",
    "Number Format": "数字格式",
    "Phase 8: Serum Development": "第八阶段：血清开发",
    "Phase Progress": "阶段进度",
    "PRESTIGE PREVIEW": "声望预览",
    "Prestiging will restart your run from Phase 0 but grant permanent bonuses based on your progress": "声望将重新启动您的运行从阶段0，但授予永久奖金根据您的进展",
    "Progress Through Campaign": "通过战役取得进展",
    "Reset Game to Initial State": "重置游戏到初始状态",
    "Restart your run with enhanced bonuses": "用增强的奖励重新开始你的跑步",
    "Save Management": "保存管理",
    "Serum synthesis capabilities are not yet available": "血清合成能力尚不具备",
    "Serum Synthesis Laboratory": "血清合成实验室",
    "Short (1.5K, 2.3M)": "短（1.5K, 2.3M）",
    "Show alerts for events and completed actions": "显示事件和已完成操作的警报",
    "Start developing the cure to save humanity": "开始研发解药来拯救人类",
    "System Information": "系统信息",
    "System Settings": "系统设置",
    "Total Ancestral Data Earned": "累计获得祖先数据",
    "Total Play Time": "总游戏时间",
    "/s NET": "/秒 净值",
    "Win:": "获胜:",
    "Resume": "返回",
    "Complete": "完成",
    "Commander's Brief": "指挥官简报",
    "COMMS": "通信",
    "Crisis response": "危机应对",
    "CRITICAL ALERTS": "重要提醒",
    "Cure": "治疗",
    "Cure all provinces": "治疗所有省份",
    "Emergency Protocol": "应急方案",
    "EMERGENCY RESPONSE": "应急响应",
    "Explore Command Center": "探索指挥中心",
    "Facilities & production": "设施&生产",
    "Final victory": "最终胜利",
    "from initial outbreak to final cure. Balance resources, research, and territorial control to prevent total collapse.": "从最初的爆发到最终的治愈平衡资源，研究和领土控制，以防止全面崩溃。",
    "Game is paused. Press SPACE when ready to begin.": "游戏暂停。准备开始时按空格键。",
    "Global Pandemic — Immediate Response Required": "全球流行病-需要立即作出反应",
    "High-risk ops": "高风险操作",
    "Lead humanity through": "引领人类",
    "Legacy": "遗产",
    "Lose:": "输：",
    "Missions": "任务",
    "Navigate freely while paused": "暂停时自由航行",
    "OUTBREAK PROTOCOL": "爆发协议",
    "Output": "输出",
    "Pause/Resume Anytime": "随时暂停/恢复",
    "Permanent upgrades each run": "每次运行的永久升级",
    "PHASE-": "阶段-",
    "Population": "人口",
    "Prestige:": "声望：",
    "PRIORITY": "优先级",
    "Progress": "进度",
    "Provinces": "省份",
    "Queued": "排队",
    "Quick Access": "快速访问",
    "Research Provisional Vaccine (Tier 4) to unlock serum development pathway.": "研究临时疫苗（第4级），解锁血清发展途径。",
    "RESPOND": "回应",
    "Secure territory": "安全区域",
    "SITREP": "情况报告",
    "SPACE": "空格键",
    "Tech advantages": "技术优势",
    "Total infection/collapse": "总感染/崩溃",
    "⏸️ Game Paused": "⏸️ 游戏已暂停",
    "Press SPACE when you're ready to begin your mission.": "准备开始任务时，请按空格键。",
    "Send Support Team": "派遣支援队",
    "ELEVATED": "提升",
    "Send Supplies": "发送物资",
    "Situation Room": "局势室",
    "spawn rate": "出生率",
    "1 situation being monitored": "1种情况正在监控中",
    "A neighboring settlement is requesting assistance with supplies or personnel.": "附近的一个定居点正在请求援助物资或人员。",
    "aid": "援助",
    "Aid Request": "援助请求",
    "aid_request": "援助请求",
    "Alert Status": "告警状态",
    "COST:": "成本:",
    "Crisis Command Center": "危机指挥中心",
    "CRISIS ELEVATED": "危机加剧",
    "CRISIS LEVEL": "危机等级",
    "Critical Situations": "危急情况",
    "Decision Archive": "决策档案",
    "decisions made": "决定",
    "Decline Request": "拒绝请求",
    "Expected Outcomes:": "预期结果:",
    "Frequency": "频率",
    "Historical record of resolved crises": "解决危机的历史记录",
    "Monitoring": "监控",
    "Neutral": "中立",
    "of 3 slots": "3个槽",
    "Real-time situation monitoring and critical decision management": "实时情况监测和关键决策管理",
    "Reputation": "声誉",
    "Resolved": "已解决",
    "Response Options": "回应选项",
    "/second": "/秒",
    "LVL": "等级",
    "LEVEL": "等级",
    "XP •": "经验值 •",
    "Total Lvls": "总等级",
    "Upgrades": "升级",
    "Net Supply": "净供应",
    "Avg": "平均",
    "Automated Factory": "自动化工厂",
    "ACTIVE": "活跃",
    "% TO NEXT LEVEL": "% 到下一级",
    "Advanced facility for synthesizing the cure serum": "用于合成治愈血清的先进设备",
    "Advanced production facility that reduces worker requirements and maximizes efficiency": "先进的生产设备，减少了对工人的需求，最大限度地提高了效率",
    "City Expansion": "城市扩张",
    "City Infrastructure": "城市基础设施",
    "Command center for construction, resource production, and city management": "建设、资源生产、城市管理指挥中心",
    "Compact": "紧凑",
    "Conducts research and generates knowledge for technological advancement": "进行研究并为技术进步提供知识",
    "Distribution Hub": "配送中心",
    "Facilities": "设施",
    "First Building": "第一个建筑",
    "free": "免费",
    "Generates energy to reduce building maintenance costs and boost production": "产生能源，减少建筑维护成本，促进生产",
    "Grid": "网格",
    "Infrastructure HQ": "基础设施总部",
    "installed": "安装",
    "Intelligence Agency": "情报机构",
    "Logistics center that accelerates serum distribution across territories": "物流中心，加快血清跨地区配送",
    "Manufactures tools and equipment, boosting overall production by 2% per level": "制造工具和设备，使每一级总产量提高2%",
    "Metropolis": "大都市",
    "Military facility that improves mission success and protects territories from threats": "提高任务成功率和保护领土免受威胁的军事设施",
    "Monument of Hope": "希望纪念碑",
    "of": "/",
    "Power Plant": "发电厂",
    "Production Overview": "生产概述",
    "Provides strategic intelligence and event prediction to improve decision making": "提供战略情报和事件预测，以提高决策",
    "Security Outpost": "安全前哨",
    "Strategic coordination hub that improves mission success and territory management": "战略协调中心，提高任务成功和领土管理",
    "Symbol of humanity's triumph and resilience, providing massive morale boost": "象征着人类的胜利和韧性，极大地鼓舞了士气",
    "% Complete": "% 完成",
    "% TO ADVANCEMENT": "% 距离进阶",
    "LAB Idle": "实验室空闲",
    "LAB LEVEL": "实验室等级",
    "unlocked": "已解锁",
    "Tier": "层级",
    "tiers cleared": "层级已清理",
    "Adaptive Distribution Protocols": "自适应分发协议",
    "Advanced agricultural techniques dramatically improve food production and sustainability": "先进的农业技术大大提高了粮食生产和可持续性",
    "Advanced biological research accelerates healing and population recovery": "先进的生物研究加速了治愈和人口的恢复",
    "Advanced command and control systems maximize operational effectiveness and coordination": "先进的指挥和控制系统最大限度地提高了作战效率和协调能力",
    "Advanced scientific research facility for breakthrough technologies": "先进的突破性技术科研设施",
    "Advanced Tactical Operations": "先进战术行动",
    "Advanced Tech": "先进的科技",
    "Agro-Engineering": "农业工程",
    "Applied Science": "应用科学",
    "Automated production systems reduce worker dependency and increase efficiency": "自动化生产系统减少了对工人的依赖，提高了效率",
    "automated_factory_ready": "自动化工厂准备就绪",
    "Basic Research": "基础研究",
    "Bio-Regeneration": "生物再生",
    "Breakthrough": "突破",
    "Breakthrough technology for synthesizing the cure serum. Dramatically increases serum synthesis success rate and speed.": "合成治愈血清的突破性技术。显著提高血清合成成功率和速度。",
    "Breakthroughs": "突破",
    "Combat and security training for survivors to defend against hostile threats": "为幸存者提供战斗和安全培训，以抵御敌对威胁",
    "command_center_ready": "指挥中心准备就绪",
    "Containment Protocols": "控制协议",
    "Cutting-edge quantum communication enables global coordination and intelligence gathering": "尖端量子通信使全球协调和情报收集成为可能",
    "Discovered": "发现",
    "Discoveries": "发现",
    "distribution_hub_ready": "配送中心准备就绪",
    "Early-stage vaccine that provides temporary immunity. Required for Alpha Synthesis research.": "提供暂时免疫力的早期疫苗。需要阿尔法合成研究。",
    "Effects": "影响",
    "Energy Grid Systems": "能源网格系统",
    "Establish satellite communication for global coordination. Provides massive production boost to Satellite buildings.": "建立卫星通信，促进全球协调。为卫星建筑提供大量的生产提升。",
    "Improved governance systems for better territory management and influence generation": "改善治理制度，以更好地管理领土和产生影响",
    "Industrial Automation": "工业自动化",
    "Integrated power infrastructure reduces maintenance costs and enables advanced facilities": "综合电力基础设施降低了维护成本，实现了先进的设施",
    "intelligence_agency_ready": "情报机构准备就绪",
    "Laboratory Intelligence": "实验室情报",
    "Military training and tactics improve mission success rates and security capabilities": "军事训练和战术提高了任务成功率和安全能力",
    "Optimized distribution systems accelerate serum deployment across all territories": "优化的分配系统加速了血清在所有地区的部署",
    "Optimized supply chain management reduces costs and increases production efficiency": "优化的供应链管理降低成本，提高生产效率",
    "power_plant_ready": "动力装置准备就绪",
    "Prerequisites": "先决条件",
    "Progress by complexity tier": "按复杂性层的进度",
    "provisional_vaccine_completed": "临时疫苗已完成",
    "Quantum Communication Network": "量子通信网络",
    "Research Laboratory": "研究实验室",
    "Research Progress": "研究进展",
    "Resource Logistics": "资源物流",
    "satellite": "卫星",
    "shelter": "避难所",
    "slots free": "空槽",
    "Standard operating procedures for infection containment and quarantine management": "感染控制和检疫管理的标准操作程序",
    "Start research to activate laboratory": "启动研究，激活实验室",
    "Strategic Command": "战略司令部",
    "synthesis_station": "综合站",
    "Tactical Training": "战术训练",
    "Technological Classification": "技术分类",
    "Territorial Administration": "领土行政",
    "DEF": "防御",
    "zones": "区域",
    "Show Details": "显示详情",
    "Unlock Territory": "解锁领土",
    "Unlock Province": "解锁省份",
    "Unstable": "不稳定",
    "Lab Idle": "实验室空闲",
    "% COVERAGE": "% 覆盖率",
    "All Territories": "所有领土",
    "All Zones Secure": "所有区域安全",
    "Avg Stability": "平均稳定度",
    "Build Defenses": "构建防御",
    "Central Hub": "中央枢纽",
    "Coastal region with strategic communication advantages": "具有战略交通优势的沿海地区",
    "Continue maintaining territorial control": "继续保持领土控制",
    "Eastern Coast": "东部沿海地区",
    "Fertile agricultural region with abundant farmland": "肥沃的农业区，有丰富的农田",
    "Former industrial center with manufacturing capabilities": "原工业中心，具有制造能力",
    "Industrial Zone": "工业园区",
    "Isolated mountain region with natural containment advantages": "具有天然封闭优势的孤立山区",
    "Maintenance Cost": "维护成本",
    "Northern Plains": "北部平原",
    "Operations Intelligence": "行动情报",
    "Protected valley ideal for shelter and farming": "受保护的山谷是理想的住所和农业",
    "Real-time territorial metrics": "实时区域度量",
    "Regional Control": "区域控制",
    "Reinforce Defenses": "加强防御",
    "Secured": "安全",
    "SECURED": "安全",
    "Southern Valley": "南部山谷",
    "Tactical overview and territory control operations": "战术概述和领土控制行动",
    "TERRITORIAL DOMINANCE •": "领土优势",
    "Threat Assessment": "威胁评估",
    "THREAT STABLE": "威胁稳定",
    "Western Mountains": "西部山区",
    "Your starting location and command center": "你的起始位置和指挥中心",
    "LOW": "低",
    "Main Menu": "主菜单",
    "MISSION LOCKED": "任务未解锁",
    "Mission Capacity": "任务容量",
    "missions unlocked": "已解锁任务",
    "Bonus: +": "加成: +",
    ", including ALL prestige points. This action CANNOT be undone!": "，包括所有声望点数。这个动作不能撤销！",
    "⚠️ PERMANENT DELETION ⚠️ This will completely erase save slot": "⚠️ 永久删除 ⚠️ 这将完全擦除保存槽",
    "Access the main menu to manage save slots, load different saves, export/import game data, or start a new game.": "访问主菜单来管理保存槽，加载不同的保存，导出/导入游戏数据，或开始一个新游戏。",
    "Active Ops": "主动行动",
    "Adjust the speed of UI animations and transitions": "调整UI动画和过渡的速度",
    "Allied Territory Assistance": "盟军领土援助",
    "Archive": "存档",
    "ASSIGN TEAM": "分配团队",
    "Automatically save progress every 30 seconds to prevent data loss": "每30秒自动保存进度，防止数据丢失",
    "Available Operations": "可用操作",
    "Average Risk": "平均风险",
    "Awards": "奖项",
    "Black Operations": "黑色行动",
    "Campaigns": "活动",
    "Choose how numbers are displayed throughout the game": "选择数字如何在游戏中显示",
    "Combat Operations": "作战行动",
    "Complete requirements to unlock these missions": "完成要求解锁这些任务",
    "Covert operations to infiltrate hostile zones and gather critical intelligence": "潜入敌对地区收集重要情报的秘密行动",
    "Create a secure trade route between territories for ongoing resource exchange": "在领土之间建立安全的贸易路线，以进行资源交换",
    "Daily Ops": "日常运维",
    "Deep Research Expedition": "深度研究考察",
    "Defensive Fortification": "防御强化",
    "Delete Save Slot": "删除保存槽位",
    "Deploy": "部署",
    "Deploy a team to rescue survivors from infected zones": "派一队人去感染区营救幸存者",
    "Deploy survivors on missions below": "在下面的任务中部署幸存者",
    "Deploy tactical teams and manage field operations": "部署战术团队并管理现场行动",
    "Deploy teams to distribute the cure serum to remote populations": "派人把治愈血清分发给偏远地区的人群",
    "Deployed Personnel": "部署人员",
    "Duration": "持续时间",
    "Elite Veterans": "精英老兵",
    "Equipment": "装备",
    "Establish contact with underground resistance movements for mutual benefit": "与地下抵抗运动建立联系，互惠互利",
    "Establish Trade Route": "建立贸易路线",
    "EXCELLENT": "优秀",
    "Extract a high-value scientist or leader from a dangerous zone": "从危险地带救出一名高价值的科学家或领导人",
    "Fortify a territory against infected hordes and hostile forces": "防御感染人群和敌对势力",
    "Game Menu": "游戏菜单",
    "in reserve": "备用",
    "Infected Horde Elimination": "消灭感染部落",
    "Supply Balance": "供给平衡",
    "Legacy Points": "遗产点数",
    "Live tracking of your operation progress": "实时跟踪您的操作进度",
    "Pause": "暂停",
    "Playtime": "游戏时长",
    "Secure Provinces": "安全的省份",
    "INSUFFICIENT RESOURCES": "资源不足",
    "Large-scale combat operation to clear infected hordes from strategic locations": "大规模战斗行动，清除战略要地的感染人群",
    "Locked Operations": "锁定操作",
    "logistics": "物流",
    "No active operations": "暂无活跃操作",
    "No Active Operations": "无活动操作",
    "Operations Command": "操作指令",
    "Operations Status": "操作状态",
    "OPS CENTER": "运维中心",
    "Organize a supply convoy to gather resources from abandoned settlements": "组织一个补给车队，从废弃的定居点收集资源",
    "Personnel & Equipment": "人员装备",
    "Provide military and humanitarian aid to allied territories under siege": "向被围困的盟国领土提供军事和人道主义援助",
    "Quarantine Breach Response": "隔离违规响应",
    "rescue": "救援",
    "Rescue Mission": "营救任务",
    "Restart Current Run": "重启当前运行",
    "Restart Run": "重新启动运行",
    "Return to Main Menu": "返回主菜单",
    "Risk": "风险",
    "Run Management": "运行管理",
    "Sample Collection": "样品收集",
    "Scout nearby territories to assess threats and identify resources": "侦察附近地区，评估威胁并确定资源",
    "Search abandoned military and research facilities for advanced technology": "搜索废弃的军事和研究设施，寻找先进技术",
    "Select a mission and assign survivors to deploy •": "选择一个任务，并分配幸存者部署",
    "Send a research team to collect infection samples for analysis": "派遣一个研究小组收集感染样本进行分析",
    "Serum Distribution Mission": "血清分配任务",
    "Show toast alerts for events and completed actions": "为事件和完成的操作显示toast警报",
    "Specialists": "专家",
    "STANDBY": "备用",
    "Start fresh from Phase 1 while keeping all your prestige points and upgrades. Perfect for trying new strategies! Prestige is only earned on Victory or Game Over.": "从阶段1重新开始，同时保留所有声望点和升级。适合尝试新策略！声望只能在胜利或游戏结束时获得。",
    "Success Rate": "成功率",
    "SUCCESS RATE": "成功率",
    "Supply Convoy": "供应车队",
    "System Behavior": "系统行为",
    "System Configuration": "系统配置",
    "TACTICAL NET ONLINE": "战术网上线",
    "Technology Salvage": "技术抢救",
    "Territory Reconnaissance": "领土侦察",
    "total veterans (Lv5+ are elite)": "累计老兵数（5级以上为精英）",
    "Underground Network": "地下网络",
    "URGENT: Contain a quarantine breach before infection spreads rapidly": "紧急：在感染迅速蔓延之前控制好隔离缺口",
    "Venture deep into infected territory to discover rare samples and research data": "冒险深入感染的领土，发现罕见的样本和研究数据",
    "Veterans": "老兵",
    "VIP Extraction": "VIP撤离",
    "All Clear": "全部清除",
    "All Situations Under Control": "所有情况都在控制之中",
    "CRISIS STABLE": "危机稳定",
    "No active crises at this time": "目前没有活跃的危机",
    "No critical events require your attention. Crisis events will appear based on game conditions.": "没有重大事件需要你的关注。危机事件将根据游戏条件出现。",
    "Current Run Statistics": "本轮游戏统计",
    "Briefings | Fixes | Balance Tweaks": "简报 | 修复 | 平衡调整",
    "Close": "关闭",
    "Run Restarted": "本轮游戏重新开始",
    "% COMPLETE": "% 完成",
    "Lv": "等级",
    "Construction Complete": "建设完成",
    "OBJECTIVES": "目标",
    "Output:": "输出:",
    "PHASE": "阶段",
    "Production Output:": "生产输出：",
    "PROGRESS": "进度",
    "TACTICAL TIP": "战术提示",
    "Total Upkeep:": "总维护：",
    "Upgrade → Lv": "升级 → 等级",
    "DONE": "完成",
    "Lab": "实验室",
    "Cost:": "成本:",
    "Continue": "继续",
    "Configure Loadout": "配置载装",
    "basic": "基础",
    "Basic Survival Gear": "基础生存装备",
    "Equipment:": "装备:",
    "Effects:": "效果:",
    "Final Deploy": "最终部署",
    "Deploy Team": "部署小队",
    "DEPLOY TEAM": "部署小队",
    "Back": "返回",
    "Back to Loadout": "返回到载装",
    "remaining": "剩余",
    "STEP": "步骤",
    "Success": "成功",
    "Success Rate Analysis": "成功率分析",
    "Success Rate:": "成功率:",
    "Team Size:": "小队规模:",
    "Team": "小队",
    "survivors": "幸存者",
    "selected": "已选择",
    "items": "物品",
    "Loadout Config": "载装配置",
    "IN PROGRESS": "进行中",
    "Abort": "中止",
    "All systems green. Mission authorization pending final confirmation.": "所有系统正常。任务授权有待最后确认。",
    "AUTHORIZE DEPLOYMENT": "授权部署",
    "Calculated across ops": "跨操作计算",
    "Complete 3 successful missions to recruit your first veteran": "成功完成3次任务，即可招募到第一位老兵",
    "Core team members assigned to this operation": "分配到这个行动的核心团队成员",
    "Deployed Survivors": "部署幸存者",
    "Equipment Loadout": "装备配装",
    "Equipment Selection": "装备选择",
    "Higher risk = more casualties on failure": "更高的风险=更多的失败伤亡",
    "Intelligence Brief": "情报概要",
    "Maximum (Never Guaranteed)": "最大值（从不保证）",
    "Minimum (Always Risk)": "最低（始终风险）",
    "Mission Authorization & Configuration": "任务授权与配置",
    "Mission Briefing": "任务简介",
    "Mission Rewards": "任务奖励",
    "Mission Risk Level": "任务风险等级",
    "No equipment selected": "未选择装备",
    "No veterans assigned": "暂无上阵老兵",
    "No veterans available": "暂无可选老兵",
    "Open tactical deployment interface": "打开战术部署界面",
    "personnel": "人员",
    "Proceed to Loadout Selection": "前往配装选择",
    "Ready for Deployment": "准备部署",
    "Recall": "召回",
    "RESCUE": "救援",
    "Review mission parameters and prepare your deployment team": "检查任务参数，准备好你的部署团队",
    "risk": "风险",
    "RISK": "风险",
    "Risk Reduction": "减少风险",
    "Select equipment to improve mission success rates •": "选择装备以提高任务成功率",
    "Standard equipment for field operations": "野外作业的标准设备",
    "TACTICAL DEPLOYMENT": "战术部署",
    "Team Composition": "团队组成",
    "Time required to complete this mission": "完成此任务所需的时间",
    "Veteran Assignment": "老兵分配",
    "Veterans:": "老兵：",
    ", Maximum:": ", 最大:",
    "influence": "影响",
    "Paused": "已暂停",
    "veteranXP": "老兵经验",
    "SPECIAL REWARDS:": "特殊奖励:",
    "More survivors = higher success rate (up to +20%). Minimum:": "更多的幸存者=更高的成功率（最多+20%）。最低:",
    "Lv.": "等级",
    "Top Consumers": "最多消耗",
    "client": "客户端",
    "CORE": "核心",
    "(see the": "(查看",
    "NETWORK": "网络",
    "LOADING OUTBREAK DATA...": "正在加载爆发数据...",
    "SYNCHRONIZING GLOBAL NETWORKS...": "同步全球网络...",
    "INITIALIZING TACTICAL SYSTEMS...": "初始化战术系统...",
    "ESTABLISHING SECURE CONNECTION...": "建立安全连接...",
    "CALIBRATING BIOSECURITY PROTOCOLS...": "校准生物安全协议...",
    "DATABASE": "数据库",
    "-side exception has occurred while loading": "加载时发生-side异常",
    "Application error: a": "应用程序错误：a",
    "browser console": "浏览器控制台",
    "for more information).": "获取更多信息)。",
    "Global Response Command System v": "全球反应指挥系统",
    "OUTBREAK": "爆发",
    "outbreak-protocol.g8hh.com.cn": "outbreak-protocol.g8hh.com.cn",
    "PROTOCOL": "协议",
    "READY FOR DEPLOYMENT": "准备部署",
    "SECURITY": "安全",
    "Empty Slot": "空槽位",
    "Global Response Command System": "全球反应指挥系统",
    "New Game": "新游戏",
    "No save data": "暂无存档",
    "Save Deleted": "存档已删除",
    "Save Slots": "存档槽位",
    "System Online": "系统在线",
    "Active Modifiers": "活跃修饰符",
    "LOGISTICS": "物流",
    "Adverse Weather": "恶劣天气",
    "Heavy rain or storms complicate the operation": "大雨或暴风雨使救援行动复杂化",
    "Survivors deployed on this mission": "执行这次任务的幸存者",
    "• Phase": "• 阶段",
    "• Run:": "• 运行:",
    "Just now": "刚刚",
    "Last played:": "最近游戏:",
    "Load": "加载",
    "Overwrite": "覆盖",
    "Run Time": "运行时长",
    "Run Time": "已保存",
    "Slot": "槽位",
    "Unlocked": "已解锁",
    "Shop (": "商店 (",
    "Repair (": "修理 (",
    "Knowledge:": "知识:",
    "Craft (": "制作 (",
    "• Blueprints unlock 25% crafting discounts for specialized equipment": "• 蓝图解锁专用装备制造25%折扣",
    "• Equipment durability decreases with use - repair it to maintain effectiveness": "• 装备耐久度会随着使用而降低，请及时维修以保持使用效果",
    "• Equipment improves mission success rates and reduces risk": "• 装备提升任务成功率，降低风险",
    "⚡ Equipment Blueprint": "⚡ 装备蓝图",
    "Arsenal Size": "兵工厂规模",
    "Blueprints": "蓝图",
    "Chain Master": "链主",
    "Check back later for new daily missions": "请稍后查看新的每日任务",
    "Complete 10 missions in a row without failure": "连续完成10个任务",
    "Complete 10 missions in under 5 minutes each": "在5分钟内完成10个任务",
    "Complete 20 missions without losing a single survivor": "完成20个任务而不损失一个幸存者",
    "Complete 30 daily missions": "完成30个日常任务",
    "Complete 50 missions successfully": "成功完成50个任务",
    "Complete a mission with 95%+ success rate and zero casualties": "以95%以上的成功率和零伤亡完成一个任务",
    "Complete all mission chains": "完成所有任务链",
    "Complete your first mission": "完成第一个任务",
    "Complete your first operation to see mission reports here": "完成您的第一次操作，查看任务报告在这里",
    "Daily Grind": "日常工作",
    "Elite Force": "精锐部队",
    "Elite personnel with unique bonuses •": "精英人员与独特的奖金",
    "Equipment Depot": "装备仓库",
    "Equipment Information": "装备信息",
    "Equipment Master": "装备大师",
    "First Deployment": "第一次部署",
    "Have 10 veterans at level 5 or higher": "有10个5级以上的老兵",
    "Influence:": "影响：",
    "INSUFFICIENT FUNDS": "资金不足",
    "Intel Points:": "情报值：",
    "Intelligence Network": "情报网",
    "Locked Rewards:": "未解锁奖励：",
    "medic": "医疗人员",
    "Mission Achievements": "任务成就",
    "Never Surrender": "永不投降",
    "No active daily missions": "没有活跃的日常任务",
    "No Man Left Behind": "不让任何人掉队",
    "No mission chains unlocked yet": "暂未解锁任务链",
    "No Mission History": "暂无任务历史",
    "No Specialists Recruited": "不招聘专家",
    "Own all basic and advanced tier equipment": "拥有所有基本和高级装备",
    "Perfect Operation": "完美操作",
    "Progress through phases to unlock story campaigns": "通关关卡解锁剧情战役",
    "Purchase intel for 25 different missions": "购买25个不同任务的情报",
    "Purchase Price": "购买价格",
    "Purchase, repair, and craft tactical equipment": "购买、修理和制作战术装备",
    "Recruit Specialist": "招聘专家",
    "Recruit your first specialist to unlock powerful bonuses": "招募你的第一个专家来解锁强大的奖励",
    "recruited": "招募",
    "Risk Taker": "冒险家",
    "Specialist": "专家",
    "Specialist Management": "专业管理",
    "Speed Runner": "竞速者",
    "STANDARD": "标准",
    "Successfully complete a mission with 70%+ risk": "以70%以上的风险成功完成一项任务",
    "Supplies:": "供应:",
    "tactician": "战术家",
    "Veteran Commander": "资深指挥官",
    "Add community spaces to improve morale and stability": "增加社区空间，提高士气和稳定性",
    "Advanced Agriculture": "高级农业",
    "Bio-Engineered Crops": "生物工程作物",
    "biolab_security": "biolab_security",
    "Build upward to house more survivors efficiently": "向上建造，以有效地容纳更多的幸存者",
    "Community Centers": "社区中心",
    "Construct climate-controlled greenhouses for year-round production": "建造可控制气候的温室，实现全年生产",
    "Cost Reduction": "降低成本",
    "Create fully independent living communities": "创建完全独立的生活社区",
    "Deploy genetically optimized crops for superior yields": "采用基因优化作物以获得更高的产量",
    "efficient_farming": "高效农业",
    "Emergency Triage": "紧急分诊",
    "emergency_mechanics": "紧急力学",
    "Field Medic Training": "野战医务人员培训",
    "Field Medicine research finished! New capabilities unlocked": "野外医学研究完成！解锁新功能",
    "field_medicine": "战地医学",
    "Greenhouse Networks": "温室网络",
    "Hydroponic Systems": "水培系统",
    "Implement advanced farming techniques for maximum efficiency": "采用先进的耕作技术以获得最大的效益",
    "Implement rapid triage protocols to reduce infection spread": "实施快速分诊方案，减少感染传播",
    "Install advanced hydroponic farming for maximum efficiency": "采用先进的水培耕作，以达到最高效率",
    "Install irrigation to improve crop yields": "安装灌溉装置以提高作物产量",
    "Integrate basic medical facilities into shelters": "将基本医疗设施纳入庇护所",
    "Irrigation Systems": "灌溉系统",
    "Medical Facilities": "医疗设施",
    "Press to resume": "按恢复键",
    "Purchase": "购买",
    "Reinforced Housing": "加强住房",
    "Requires building level": "需要建筑等级",
    "Requires technology:": "需要技术:",
    "Research Complete": "研究完成",
    "resilient_society": "弹性社会",
    "Self-Sustaining Habitats": "自我维持的栖息地",
    "Strengthen shelter structures for better protection and efficiency": "加强住房结构，提高保护和效率",
    "Sub-Upgrades (": "次要升级 (",
    "Train civilians in basic medical care to boost morale": "对平民进行基本医疗培训以鼓舞士气",
    "Vertical Expansion": "纵向扩张",
    "Worker Efficiency": "工人效率",
    "Hide Details": "隐藏详情",
    "Purchased": "已购买",
    "SHOW ALL": "显示全部",
    "slot": "槽位",
    "Phase Complete": "阶段完成",
    "% Risk": "% 风险",
    "🏆 First Deployment": "🏆首次部署",
    "🚨 CRITICAL: Supply Convoy Under Attack": "🚨紧急：补给车队受到攻击",
    "1 zone needs stabilization": "1区域需要稳定",
    "Build a Radio Tower": "建造一座无线电塔",
    "COMMUNICATION NETWORK": "通信网络",
    "Daily Mission Complete!": "每日任务完成！",
    "Emergency medical equipment to save lives": "抢救生命的紧急医疗设备",
    "Emergency Response (Phase 1) objectives achieved!": "应急响应（第一阶段）目标实现！",
    "Equipment Bonus": "装备加成",
    "Field Medical Supplies": "战地医疗用品",
    "Friendly locals provide assistance": "友好的当地人提供帮助",
    "Local Militia Support": "当地民兵支持",
    "Monitor Closely": "密切监控",
    "Questionable": "可疑",
    "Reduce infection rate below 55%": "将感染率降低到55%以下",
    "Risk Reduced": "风险降低",
    "Stabilize Province": "稳定省份",
    "Stabilize Territory": "稳定地区",
    "supply_convoy_ambush": "补给车队伏击",
    "Survivor Protection": "幸存者保护",
    "UNSTABLE": "不稳定",
    "Success (": "成功 (",
    "SUCCESS": "成功",
    "Special:": "特殊:",
    "Rewards": "奖励",
    "Rewards Claimed:": "领取的奖励:",
    "% Bonus": "% 加成",
    "% bonus rewards": "% 加成奖励",
    "\" mission to earn": "\" 任务以获得",
    "All Missions (": "全部任务 (",
    "Average Level": "平均等级",
    "Completion Rewards:": "完成奖励:",
    "knowledge": "知识",
    "Mission": "任务",
    "Missions Completed": "任务已完成",
    "All available equipment purchased!": "所有可用的装备都已购买！",
    "Click to view detailed after-action report": "单击查看详细的行动后报告",
    "Complete achievements and mission chains to unlock blueprints": "完成成就和任务链以解锁蓝图",
    "Complete missions with veteran XP rewards to recruit veterans": "用经验值奖励完成任务来招募老兵",
    "Supply Convoy": "供应车队",
    "Deploy and successfully complete the \"": "部署并成功完成",
    "Failure (": "失败(",
    "First Response Training": "第一反应训练",
    "Highest Level": "最高等级",
    "How to Complete:": "如何完成：",
    "Introductory mission sequence to train your operations team": "入门任务序列训练您的操作团队",
    "MODERATE": "适中",
    "most experienced survivors": "最有经验的幸存者",
    "Next Mission:": "下一个任务:",
    "No blueprints unlocked yet": "蓝图还没有解锁",
    "No missions match the selected filter": "没有任务匹配所选的过滤器",
    "No veterans yet": "暂无老兵",
    "Personnel": "人员",
    "Purchase this equipment for your arsenal": "为你的军火库购买这个装备",
    "Reduces mission risk, improving success rate": "降低任务风险，提高成功率",
    "Top": "前",
    "Total Veterans": "累计老兵数",
    "Unlock more through research and progression": "通过研究和进展解锁更多",
    "veteran_recruit": "招募老兵",
    "⚠️ URGENT: Local Outbreak Detected": "⚠️ 紧急：检测到本地爆发",
    "infection": "感染",
    "high": "高",
    "outbreak_local": "本地爆发",
    "outbreak": "爆发",
    "% Success": "% 成功",
    "Satellite surveillance has detected a surge of infected activity in a nearby settlement. Thermal imaging shows hundreds of signatures. The settlement is requesting immediate assistance. Time is critical.": "卫星监测发现，在附近的一个定居点，感染活动激增。热成像显示有数百个信号。和解协议要求立即提供援助。时间很关键。",
    "Conserve resources for your primary base. The settlement is on its own.": "为你的主要基地保留资源。和解协议是独立的。",
    "Coordinate Emergency Evacuation": "协调紧急疏散",
    "crisis": "危机",
    "CRITICAL: Morale Collapse": "关键：士气崩溃",
    "Deploy containment teams to seal off the settlement. Harsh but effective.": "部署控制小组封锁定居点。严厉但有效。",
    "Dispatch Medical Strike Team": "派遣医疗突击队",
    "Enforce Strict Quarantine": "严格检疫",
    "Extract as many survivors as possible before the infection spreads uncontrollably.": "在感染无法控制地蔓延之前，尽可能多地救出幸存者。",
    "Local Outbreak Detected": "检测到本地爆发",
    "Notorious": "臭名昭著",
    "Prioritize Central Hub Resources": "优先考虑中心枢纽资源",
    "Rep": "声誉",
    "Requires containment protocols technology": "需要收容协议技术",
    "Requires containment unit": "需要隔离装置",
    "Send your best medical personnel with full protective gear and treatment supplies.": "派遣你们最好的医务人员携带全套防护装备和治疗用品。",
    "time sensitive": "时效性",
    "A neighboring settlement has fallen. Hundreds of refugees are approaching your gates, begging for sanctuary. Your resources are already stretched thin, but turning them away might doom them.": "邻近的一个定居点已经沦陷。数以百计的难民正在靠近你的大门，乞求庇护。你的资源已经很紧张了，但拒绝他们可能会让他们陷入困境。",
    "Accept All Refugees": "接纳所有难民",
    "Accept Only Skilled Workers": "只接受技术工人",
    "Accept refugees but only after thorough medical and security screening.": "接受难民，但必须经过彻底的医疗和安全检查。",
    "Close the Gates": "关上大门",
    "ethical": "合乎道德",
    "Harsh but necessary. Your settlement's survival comes first.": "苛刻但必要。你们定居点的生存是第一位的。",
    "humanitarian": "人道主义",
    "Implement Strict Screening": "严格筛选",
    "Infection rate:": "感染率:",
    "Massive Refugee Influx": "大量难民涌入",
    "medium": "中",
    "more effects...": "更多的影响……",
    "Open your gates. Humanity must stand together, no matter the cost.": "打开你的大门。人类必须站在一起，不管付出什么代价。",
    "Requires clinic": "需要诊所",
    "resource strain": "资源紧张",
    "Select refugees with valuable skills. Send the rest to other settlements.": "选择具有宝贵技能的难民。把剩下的人送到其他定居点去。",
    "ACTIVE BONUSES": "活跃加成",
    "Defense reduces decay by": "防御降低衰减",
    "GOOD": "不错",
    "HIGH": "高",
    "STABILITY": "稳定",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "KN": "知识",
    "/s)": "/秒)",
    "SP": "供应",
    "SV": "幸存者",
    "RF": "供应",
    "IF": "影响力",
    "CN": "知识",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "%": "%",
    "/": "/",
    "Gityx游戏": "Gityx游戏",
    "~": "~",
    "•": "•",
    "×": "×",
    "N/A": "N/A",
    "(+": "(+",
    "(-": "(-",
    "% •": "% •",
    "⚡": "⚡",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Aid Request - ": "援助请求-",
    "Normal (": "正常 (",
    "Locked Until Phase ": "锁定直到阶段 ",
    "Morale: ": "士气: ",
    "Influence: ": "影响: ",
    "Min:": "最小:",
    "Max:": "最大:",
    "Full (": "完整 (",
    "DAILY: ": "日常: ",
    "Infection Rate: ": "感染率: ",
    "Global Production: ": "全局生产: ",
    "Knowledge: ": "知识: ",
    "Survivors: ": "幸存者: ",
    "Global Stability: ": "全球稳定性: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " ACTIVE SITUATIONS": " 积极情况",
    " Active": " 活跃",
    "/s": "/秒",
    " STEPS COMPLETE": " 步骤完成",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^\+([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)K IF$/, '$1K 影响力'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)m ago$/, '$1 分钟前'],
    [/^([\d\.,]+) phases$/, '$1 阶段'],
    [/^([\d\.,]+) REMAINING$/, '$1 剩余'],
    [/^\+(.+) survivors · \+(.+) supplies$/, '+$1 幸存者 · +$2 供应'],
    [/^\+(.+) supplies · \+(.+) influence$/, '+$1 供应 · +$2 影响'],
    [/^([\d\.,]+) experiment in progress$/, '$1 实验进行中'],
    [/^([\d\.,]+)h ([\d\.,]+)m$/, '$1 小时 $2 分钟'],
    [/^Build Refugee Shelter to level ([\d\.,]+)$/, '将难民收容所建设到等级 $1'],
    [/^Phase ([\d\.,]+)$/, '阶段 $1'],
    [/^CITY LVL ([\d\.,]+)$/, '城市等级 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^LAB LVL ([\d\.,]+)$/, '实验室等级 $1'],
    [/^STEP ([\d\.,]+)$/, '步骤 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Supply Farm upgraded to level ([\d\.,]+)$/, '补给农场 升级到了等级 $1'],
    [/^Reach ([\d\.,]+) survivors$/, '达到 $1 幸存者'],
    [/^Upgrade Shelter to level ([\d\.,]+)$/, '升级 避难所 到等级 $1'],
    [/^Refugee Shelter to level ([\d\.,]+)$/, '难民避难所 升级到了等级 $1'],
    [/^Refugee Shelter upgraded to level ([\d\.,]+)$/, '难民避难所 升级到了等级 $1'],
    [/^Build Supply Farm to level ([\d\.,]+)$/, '建造 补给农场 到等级 $1'],
    [/^Requires Campaign Phase ([\d\.,]+)$/, '需要活动阶段 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);