/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "REWARDS": "奖励",
    "Save Slot": "存档槽位",
    "Safe": "安全",
    "Save Game": "保存游戏",
    "Build": "建造",
    "STABLE": "稳定",
    "Buildings": "建筑",
    "Command": "指挥",
    "Updates": "更新",
    "Upkeep": "维护",
    "View Events": "查看事件",
    "Territory": "领土",
    "Survivors": "幸存者",
    "Supplies": "供应",
    "Safe Zones": "安全区",
    "Stability": "稳定性",
    "Researched": "已研究",
    "Serum Lab": "血清实验室",
    "Research Technologies": "研究技术",
    "RESEARCH TECH": "研究技术",
    "Research": "研究",
    "Research output": "研究成果",
    "RED ALERT": "红色警报",
    "Queue Slots": "队列槽位",
    "Knowledge": "知识",
    "Events": "事件",
    "Critical": "暴击",
    "Command Center": "指挥中心",
    "Campaign Phase": "活动阶段",
    "Operations": "操作",
    "Build Infrastructure": "建造基础设施",
    "Build Supply Farm to level 5 to sustain ongoing upkeep": "建造补给场至5级以维持持续的维护",
    "Central operations dashboard for outbreak management": "用于爆发管理的中央操作指示板",
    "Expand Territory": "扩张领土",
    "Containment": "控制",
    "Active Events": "活跃事件",
    "Active Missions": "活跃任务",
    "Active Operations": "活跃操作",
    "Go to": "前往",
    "IN DEVELOPMENT": "开发中",
    "Expand": "展开",
    "Intermediate step • Not the final cure": "中间步骤 • 不是最终的解决方案",
    "Phase Reached": "阶段达到",
    "Production": "生产",
    "Play Time": "游戏时长",
    "Prestige bonuses provide starting resources, production boosts, and cost reductions": "声望奖励提供初始资源、产量提升和成本降低",
    "Tip:": "提示:",
    "Technologies": "科技",
    "Try Again": "重试",
    "View Event": "查看事件",
    "Workers": "工人",
    "/s recruitment": "/秒 招聘",
    "Assigned": "分配的",
    "Available": "可用",
    "Controlled": "受控",
    "Morale": "士气",
    "Infrastructure": "基础设施",
    "Infection": "感染",
    "Influence": "影响力",
    "Critical Alerts": "重要提醒",
    "Diplomacy gain": "外交收益",
    "Outbreak Protocol": "爆发协议",
    "Net change": "净变化",
    "Phase": "阶段",
    "Quick Start Guide": "快速入门指南",
    "Start by building Shelters and Farms to generate\n                          Survivors and Supplies—keep an eye on upkeep and pause\n                          buildings if supplies dip": "从建造庇护所和农场开始，生成\n幸存者和补给——注意维护，如果补给减少，暂停\n建筑",
    "Start by building Shelters and Farms to generate Survivors and Supplies—keep an eye on upkeep and pause buildings if supplies dip": "从建造避难所和农场开始，以产生生还者和供给——注意维护，如果供给下降，暂停建造",
    "Build Radio Towers to gain Influence, but only keep\n                          them online when your supply trend is positive": "建造无线电塔来获得影响力，但只有当你的供应趋势是积极的时候才能保持它们在线",
    "Build Radio Towers to gain Influence, but only keep them online when your supply trend is positive": "建造无线电塔来获得影响力，但只有当你的供应趋势是积极的时候才能保持它们在线",
    "Build Labs to generate Knowledge, then research technologies to unlock new capabilities": "建立实验室以产生知识，然后研究技术以解锁新功能",
    "Watch the supply trend in the header—if it turns red, pause non-essential buildings until you recover, then continue pushing objectives.": "观察标题中的供给趋势——如果它变成红色，暂停非必要的建筑直到你恢复，然后继续推进目标。",
    "Active": "活跃",
    "In Progress": "进度",
    "Total Levels": "总等级",
    "Build Radio Tower to level 3 and maintain a positive supply trend": "建立无线电塔到3级，并保持积极的供应趋势",
    "active event(s) requiring attention": "需要关注的活跃事件",
    "Immediate attention required": "需要立即注意",
    "Ancestral Data Earned": "原始数据获得",
    "Breakdown": "故障",
    "Build Containment Units and stabilize red provinces": "建立控制单元，稳定红色省份",
    "Building Levels": "建筑等级",
    "CRITICAL": "危重",
    "CRITICAL INFECTION": "危重感染",
    "CRITICAL: Infection at 100%": "危重：100%感染",
    "Field Missions": "野外任务",
    "In Queue": "在队列中",
    "OPERATION FAILED": "操作失败",
    "The infection has completely overwhelmed humanity. The outbreak is unstoppable.": "这种感染已经使人类不堪重负。爆发是不可阻挡的。",
    "Total Prestige Level:": "总声望等级:",
    "WARNING": "警告",
    "Prestige Restart": "声望重启",
    "Infection rate critical:": "感染率危急：",
    "Required for serum development": "血清发展所需",
    "Research Provisional Vaccine (Tier 4) to unlock": "研究临时疫苗（第四阶）解锁",
    "Provisional Vaccine": "临时疫苗",
    "slots": "槽位",
    "Research Queue": "研究队列",
    "Research completion by tier": "按层级划分的研究完成情况",
    "Resilient Society": "弹性社会",
    "Synthetic Drugs": "合成药物",
    "Tier Progress Overview": "层级进度概览",
    "TIER": "层级",
    "Technologies unlocked": "技术解锁",
    "PREREQUISITES": "先决条件",
    "Mobile Labs": "移动实验室",
    "Locked": "未解锁",
    "lab": "实验室",
    "Infection Rate": "感染率",
    "IDLE": "空闲",
    "Improved agricultural techniques for better supply production": "改进农业技术，提高供应生产",
    "Improved protocols for containing and isolating infected areas": "改进了控制和隔离感染区域的方案",
    "Establish satellite communication for global coordination": "建立卫星通信，促进全球协调",
    "farm": "农业",
    "Efficient Farming": "高效农业",
    "EFFECTS": "效果",
    "Early-stage vaccine that provides temporary immunity": "提供暂时免疫力的早期疫苗",
    "Levels": "等级",
    "First level output:": "一级输出:",
    "Defense": "防御",
    "Net Flow": "网络流",
    "Research Lab": "研究实验室",
    "Radio Tower": "无线电塔",
    "Upkeep: -": "保养: -",
    "Supply Farm": "供应农场",
    "Support": "支持",
    "supplies": "供应",
    "Satellite Uplink": "卫星上行",
    "Serum Synthesis Station": "血清合成站",
    "Specialized facility for containing and studying the infection": "用于控制和研究感染的专门设施",
    "Boost it by resolving crises favorably, providing aid, and keeping supplies steady.": "通过积极解决危机、提供援助和保持供应稳定来促进它。",
    "Captures survivor optimism and willingness to follow orders. Strong morale cushions stability and infection swings.": "捕捉到幸存者的乐观和服从命令的意愿。强大的士气缓冲了稳定和感染的波动。",
    "Containment Coefficient": "控制系数",
    "Drops when morale collapses, infection surges, or territories slip into red status without containment.": "当士气崩溃，感染激增，或领土在没有遏制的情况下进入红色状态时掉落。",
    "Falling behind on research or losing critical infrastructure will stagnate containment gains.": "在研究方面落后或失去关键基础设施将使防控成果停滞不前。",
    "Global Morale": "全球士气",
    "Global Stability": "全球稳定",
    "Indicates how aggressively the outbreak is spreading at this moment. Critical levels can trigger game-ending scenarios if ignored.": "显示了目前疫情蔓延的速度。如果忽视了关键关卡便会触发游戏结局。",
    "Infection Pressure": "感染压力",
    "Invest in research labs, containment units, and specialised technologies to elevate this value.": "投资研究实验室、隔离设施和专业技术来提升这一价值。",
    "It climbs rapidly when morale is low, red provinces stack up, or emergencies are left unresolved.": "当士气低落、红色省份堆积或紧急情况未得到解决时，它会迅速攀升。",
    "Lower the pressure with containment research, stabilised provinces, and events that secure medical or logistic support.": "通过遏制研究、稳定省份和确保医疗或后勤支持的事件来降低压力。",
    "Measures how orderly and coordinated your response network is. Higher stability slows future infection growth and keeps crises at bay.": "衡量你的反应网络有多有序和协调。更高的稳定性减缓了未来感染的增长，避免了危机的发生。",
    "Rises when you secure provinces, resolve events decisively, and maintain healthy morale across survivors.": "当你占领省份，果断地解决事件，并在幸存者中保持健康的士气时上升。",
    "Shows how much infection you suppress every tick. The higher the coefficient, the more the infection rate declines naturally.": "显示出你能抑制多少感染。系数越高，感染率自然下降越多。",
    "Starvation, high casualties, and hard-line ethical choices will erode morale over time.": "随着时间的推移，饥饿、高伤亡和强硬的道德选择将削弱士气。",
    "/s supplies": "/秒 供应",
    "% utilized": "% 利用率",
    "active": "活跃",
    "Advanced education center that accelerates research and boosts morale": "高级教育中心，加速研究，鼓舞士气",
    "All Buildings": "所有建筑",
    "available": "可用",
    "avg": "平均",
    "Broadcasts messages and coordinates efforts, generating influence": "广播信息和协调工作，产生影响",
    "Containment Unit": "收容单元",
    "Global communication network that reduces events and improves containment": "减少事件并改善遏制的全球通信网络",
    "Manufactures tools and equipment, boosting overall production by 0.8% per level": "制造工具和设备，每级提高0.8%的整体产量",
    "Medical Clinic": "医疗诊所",
    "University": "大学",
    "Workforce": "劳动力",
    "workshop": "工坊",
    "Workshop": "工坊",
    "Treats the infected and improves public health": "治疗感染者，改善公众健康",
    "Refugee Shelter": "难民收容所",
    "Provides housing for survivors and slowly increases population": "为幸存者提供住房，慢慢增加人口",
    "Produces supplies through agriculture and resource gathering": "通过农业和资源收集生产供给品",
    "New Event": "新事件",
    "Notification": "通知",
    "Watch the\n                      supply trend in the header—if it turns red, pause\n                      non-essential buildings until you recover, then continue\n                      pushing objectives.": "观察顶部供给趋势——如果它变成红色，暂停非必要的建筑直到你恢复，然后继续推进目标。",
    "% complete": "% 完成",
    "Advanced Containment": "高级收容",
    "Advanced orbital communication network for global reach": "先进的全球轨道通信网络",
    "advanced_decontamination": "高级去污",
    "ALL TIERS": "所有层级",
    "Alpha Synthesis": "阿尔法合成",
    "Available Knowledge": "可用知识",
    "Basic medical training for survivors to reduce infection spread": "为幸存者提供基本医疗培训，以减少感染传播",
    "Biolab Security": "生物学实验室安全",
    "Breakthrough technology for synthesizing the cure serum": "合成治愈血清的突破性技术",
    "Build Labs to generate Knowledge, then research\n                          technologies to unlock new capabilities": "建立实验室以产生知识，然后研究技术以解锁新功能",
    "Build Radio Tower to level 3 and maintain a positive\n                        supply trend": "建立无线电塔到3级，并保持积极的\n供应趋势",
    "Civilian Networks": "民用网络",
    "clinic": "诊所",
    "Develop synthetic medications to treat symptoms and boost morale": "开发合成药物来治疗症状，鼓舞士气",
    "Emergency containment protocol for critical outbreak situations": "紧急疫情控制方案",
    "Emergency Mechanics": "应急机制",
    "Enhanced security protocols for research facilities": "加强研究设施的安全协议",
    "Field Medicine": "领域医学",
    "HIDE RESEARCHED": "隐藏的研究",
    "No active research. Select a technology below to begin.": "没有积极的研究。选择下面的技术开始。",
    "Orbital Communications": "轨道通信",
    "Organize civilian communication networks for better coordination": "组织民用通信网络，加强协调",
    "Overall Progress": "总体进展",
    "Portable research facilities for field deployment": "用于野外部署的便携式研究设施",
    "Protocol Zero": "协议为零",
    "radio_tower": "无线电塔",
    "Ready to research": "准备好研究了吗？",
    "Research & Development": "研发",
    "Research currency for unlocking technologies": "研究解锁技术的货币",
    "satellite_surveillance": "卫星监视",
    "satlink_upgrade": "卫星链路升级",
    "serum_synthesis": "血清合成",
    "Social programs to build a stronger, more resilient community": "建立一个更强大、更有韧性的社区的社会项目",
    "Train survivors in basic repair and maintenance skills": "培训幸存者基本的维修和保养技能",
    "Unlock advanced technologies to improve your response capabilities": "解锁先进技术以提高您的响应能力",
    "Unlocks Feature": "解锁功能",
    "⚠️ This will permanently delete all progress, save files, and settings. This action cannot be undone.": "⚠️ 这将永久删除所有进度、保存文件和设置。此操作不能撤消。",
    "LOCKED": "未解锁",
    "Load Game": "加载游戏",
    "New Total:": "新合计：",
    "Prestige Now": "立即声望",
    "Safe Provinces": "安全的省份",
    "Auto-Save": "自动保存",
    "Auto-Save Status": "自动保存状态",
    "Animation Speed": "动画速度",
    "SYSTEM": "系统",
    "Slot 1 - Primary Save": "槽位 1 - 主存档",
    "Version": "版本",
    "EXPORT / IMPORT": "导出 / 导入",
    "Import Save File": "导入存档文件",
    "Export Save File": "导出存档文件",
    "Display & Interface": "显示 & 界面",
    "Current Phase": "当前阶段",
    "Danger Zone": "危险区",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "SV": "生存",
    "/s": "/秒",
    "RF": "RF",
    "IF": "IF",
    "CN": "CN",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "%": "%",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Aid Request - ": "援助请求-",
    "Normal (": "正常 (",
    "Locked Until Phase ": "锁定直到阶段 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)h ([\d\.,]+)m$/, '$1 小时 $2 分钟'],
    [/^Build Refugee Shelter to level ([\d\.,]+)$/, '将难民收容所建设到等级 $1'],
    [/^Phase ([\d\.,]+)$/, '阶段 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);